import '../models/member.dart';

const List<Member> demoMembers = <Member>[
  Member(
    id: 'ceo-001',
    name: 'Ava Chen',
    role: 'Principal Software Engineer',
    department: 'Engineering',
    team: 'Platform',
  ),
  Member(
    id: 'eng-mgr-001',
    name: 'Noah Patel',
    role: 'Engineering Manager',
    department: 'Engineering',
    team: 'Platform',
    managerId: 'ceo-001',
  ),
  Member(
    id: 'eng-001',
    name: 'Priya Sharma',
    role: 'Software Development Engineer III (SDE III)',
    department: 'Engineering',
    team: 'Core Services',
    managerId: 'eng-mgr-001',
  ),
  Member(
    id: 'eng-002',
    name: 'Liam Johnson',
    role: 'Software Development Engineer II (SDE II)',
    department: 'Engineering',
    team: 'Core Services',
    managerId: 'eng-mgr-001',
  ),
  Member(
    id: 'product-001',
    name: 'Maya Rodriguez',
    role: 'Product Manager',
    department: 'Product',
    team: 'Growth',
    managerId: 'ceo-001',
  ),
  Member(
    id: 'ops-001',
    name: 'Ethan Brooks',
    role: 'DevOps Engineer',
    department: 'Operations',
    team: 'Infra',
    managerId: 'ceo-001',
  ),
  Member(
    id: 'qa-001',
    name: 'Sophia Ali',
    role: 'QA / Test Engineer',
    department: 'Operations',
    team: 'Quality',
    managerId: 'ops-001',
  ),
  Member(
    id: 'hr-001',
    name: 'Daniel Kim',
    role: 'Technical Consultant',
    department: 'HR',
    team: 'People Ops',
    managerId: 'ceo-001',
  ),
  Member(
    id: 'mkt-001',
    name: 'Isabella Singh',
    role: 'Senior Software Engineer',
    department: 'Marketing',
    team: 'Brand Systems',
    managerId: 'product-001',
  ),
  Member(
    id: 'eng-003',
    name: 'Lucas Martin',
    role: 'Software Development Engineer I (SDE I)',
    department: 'Engineering',
    team: 'Platform',
    managerId: 'eng-001',
  ),
];
